CREATE TABLE `uk_datadic` (
  `ID` varchar(32) NOT NULL,
  `NAME` varchar(32) DEFAULT NULL,
  `TITLE` varchar(32) DEFAULT NULL,
  `CODE` varchar(32) DEFAULT NULL,
  `PARENTID` varchar(32) DEFAULT NULL,
  `TYPE` varchar(32) DEFAULT NULL,
  `MEMO` varchar(255) DEFAULT NULL,
  `ORGI` varchar(32) DEFAULT NULL,
  `STATUS` varchar(32) DEFAULT NULL,
  `CREATETIME` timestamp NULL DEFAULT NULL,
  `UPDATETIME` timestamp NULL DEFAULT NULL,
  `CREATER` varchar(255) DEFAULT NULL,
  `PUBLISHEDTYPE` varchar(32) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `TABTYPE` varchar(32) DEFAULT NULL,
  `DSTYPE` varchar(32) DEFAULT NULL,
  `DSTEMPLET` varchar(255) DEFAULT NULL,
  `SORTINDEX` int(11) DEFAULT NULL,
  `DICTYPE` varchar(32) DEFAULT NULL,
  `ICONCLASS` varchar(100) DEFAULT NULL,
  `CSSSTYLE` varchar(255) DEFAULT NULL,
  `AUTHCODE` varchar(100) DEFAULT NULL,
  `DEFAULTMENU` tinyint(4) DEFAULT NULL,
  `DATAID` varchar(32) DEFAULT NULL,
  `DICICON` varchar(32) DEFAULT NULL,
  `CURICON` varchar(32) DEFAULT NULL,
  `BGCOLOR` varchar(32) DEFAULT NULL,
  `CURBGCOLOR` varchar(32) DEFAULT NULL,
  `MENUPOS` varchar(32) DEFAULT NULL,
  `DISTITLE` varchar(100) DEFAULT NULL,
  `NAVMENU` tinyint(4) DEFAULT '0',
  `QUICKMENU` tinyint(4) DEFAULT '0',
  `PROJECTID` varchar(32) DEFAULT NULL,
  `SPSEARCH` tinyint(4) DEFAULT NULL,
  UNIQUE KEY `SQL121227155530400` (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `uk_report` (
  `ID` varchar(32) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `REPORTTYPE` varchar(32) DEFAULT NULL,
  `TITLE` varchar(255) DEFAULT NULL,
  `ORGI` varchar(32) DEFAULT NULL,
  `OBJECTCOUNT` int(11) DEFAULT NULL,
  `DICID` varchar(32) DEFAULT NULL,
  `CREATETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DESCRIPTION` longtext,
  `HTML` longtext,
  `REPORTPACKAGE` varchar(255) DEFAULT NULL,
  `USEACL` varchar(32) DEFAULT NULL,
  `status` varchar(32) DEFAULT NULL,
  `rolename` text,
  `userid` text,
  `blacklist` text,
  `REPORTCONTENT` longtext,
  `reportmodel` varchar(32) DEFAULT NULL,
  `updatetime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `creater` varchar(255) DEFAULT NULL,
  `reportversion` int(11) DEFAULT NULL,
  `publishedtype` varchar(32) DEFAULT NULL,
  `tabtype` varchar(32) DEFAULT NULL,
  `USERNAME` varchar(32) DEFAULT NULL,
  `USEREMAIL` varchar(255) DEFAULT NULL,
  `CACHE` smallint(6) DEFAULT NULL,
  `EXTPARAM` varchar(255) DEFAULT NULL,
  `TARGETREPORT` varchar(32) DEFAULT NULL,
  `DATASTATUS` tinyint(4) DEFAULT NULL,
  `CODE` varchar(100) DEFAULT NULL,
  `SOURCE` varchar(50) DEFAULT NULL,
  `VIEWTYPE` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE uk_templet ADD layoutcols int default 0;


CREATE TABLE `uk_reportmodel` (
  `id` varchar(50) NOT NULL,
  `posx` varchar(50) DEFAULT NULL,
  `posy` varchar(50) DEFAULT NULL,
  `poswidth` varchar(50) DEFAULT NULL,
  `posheight` varchar(50) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `code` varchar(50) DEFAULT NULL,
  `reportid` varchar(50) DEFAULT NULL,
  `modeltype` varchar(50) DEFAULT NULL,
  `sortindex` int(11) DEFAULT NULL,
  `stylestr` varchar(50) DEFAULT NULL,
  `labeltext` varchar(50) DEFAULT NULL,
  `cssclassname` varchar(50) DEFAULT NULL,
  `mposleft` varchar(50) DEFAULT NULL,
  `mpostop` varchar(50) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `exchangerw` tinyint(4) DEFAULT '0',
  `publishedcubeid` varchar(50) DEFAULT NULL,
  `rowdimension` text,
  `coldimension` text,
  `measure` varchar(50) DEFAULT NULL,
  `dstype` varchar(50) DEFAULT NULL,
  `dbtype` varchar(50) DEFAULT NULL,
  `orgi` varchar(50) DEFAULT NULL,
  `objectid` varchar(50) DEFAULT NULL,
  `createtime` datetime DEFAULT NULL,
  `filterstr` varchar(50) DEFAULT NULL,
  `sortstr` varchar(50) DEFAULT NULL,
  `viewtype` varchar(50) DEFAULT NULL,
  `chartemplet` varchar(50) DEFAULT NULL,
  `chartype` varchar(50) DEFAULT NULL,
  `chartdatatype` varchar(50) DEFAULT NULL,
  `chart3d` varchar(50) DEFAULT NULL,
  `xtitle` varchar(50) DEFAULT NULL,
  `ytitle` varchar(50) DEFAULT NULL,
  `charttitle` varchar(50) DEFAULT NULL,
  `displayborder` varchar(50) DEFAULT NULL,
  `bordercolor` varchar(50) DEFAULT NULL,
  `displaydesc` varchar(50) DEFAULT NULL,
  `formdisplay` varchar(50) DEFAULT NULL,
  `labelstyle` varchar(50) DEFAULT NULL,
  `formname` varchar(50) DEFAULT NULL,
  `defaultvalue` varchar(50) DEFAULT NULL,
  `querytext` varchar(50) DEFAULT NULL,
  `tempquey` varchar(50) DEFAULT NULL,
  `displaytitle` tinyint(4) DEFAULT '0',
  `clearzero` tinyint(4) DEFAULT '0',
  `titlestr` varchar(50) DEFAULT NULL,
  `width` varchar(50) DEFAULT NULL,
  `height` varchar(50) DEFAULT NULL,
  `widthunit` varchar(50) DEFAULT NULL,
  `heightunit` varchar(50) DEFAULT NULL,
  `defheight` varchar(50) DEFAULT NULL,
  `defwidth` varchar(50) DEFAULT NULL,
  `neckwidth` varchar(50) DEFAULT NULL,
  `neckheight` varchar(50) DEFAULT NULL,
  `extparam` varchar(50) DEFAULT NULL,
  `marginright` varchar(50) DEFAULT NULL,
  `colorstr` varchar(50) DEFAULT NULL,
  `start` varchar(50) DEFAULT NULL,
  `end` varchar(50) DEFAULT NULL,
  `rowformatstr` varchar(50) DEFAULT NULL,
  `colformatstr` varchar(50) DEFAULT NULL,
  `publishtype` varchar(50) DEFAULT NULL,
  `editview` varchar(50) DEFAULT NULL,
  `expandbtm` tinyint(4) DEFAULT '0',
  `expandrgt` tinyint(4) DEFAULT '0',
  `curtab` varchar(50) DEFAULT NULL,
  `hiddencolstr` varchar(50) DEFAULT NULL,
  `eventstr` varchar(50) DEFAULT NULL,
  `dsmodel` varchar(50) DEFAULT NULL,
  `html` text,
  `sqldialect` varchar(255) DEFAULT NULL,
  `pagesize` int(11) DEFAULT NULL,
  `isloadfulldata` varchar(50) DEFAULT NULL,
  `isexport` tinyint(4) DEFAULT '0',
  `selectdata` tinyint(4) DEFAULT '0',
  `exporttitle` varchar(50) DEFAULT NULL,
  `colsize` int(11) DEFAULT NULL,
  `sorttype` varchar(50) DEFAULT NULL,
  `sortname` varchar(50) DEFAULT NULL,
  `mid` varchar(32) DEFAULT NULL,
  `parentid` varchar(32) DEFAULT NULL,
  `templetid` varchar(32) DEFAULT NULL,
  `colspan` int(11) DEFAULT NULL,
  `colindex` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE uk_system_message ADD moreparam text;
ALTER TABLE uk_templet ADD datatype varchar(32) default null;
ALTER TABLE uk_templet ADD charttype varchar(32) default null;

